### ISSUE TITLE
Error after 1.1.0 installation

### ISSUE THREAD

**Issue by VincentGardeux** [linlabbcm/rose2#10]
Hello,

I was using rose2 v1.0.1 until now, and it was working like a charm.
I tried to update to the last version (1.1.0) and now I cannot run rose2 anymore.

The installation goes fine, but then, when I try to run rose2, it fails.
Here is the error message:

```
Traceback (most recent call last):
  File "/bin/rose2", line 11, in <module>
    load_entry_point('rose2==1.1.0', 'console_scripts', 'rose2')()
  File "/usr/lib/python3.6/site-packages/pkg_resources/__init__.py", line 490, in load_entry_point
    return get_distribution(dist).load_entry_point(group, name)
  File "/usr/lib/python3.6/site-packages/pkg_resources/__init__.py", line 2859, in load_entry_point
    return ep.load()
  File "/usr/lib/python3.6/site-packages/pkg_resources/__init__.py", line 2450, in load
    return self.resolve()
  File "/usr/lib/python3.6/site-packages/pkg_resources/__init__.py", line 2456, in resolve
    module = __import__(self.module_name, fromlist=['__name__'], level=0)
  File "/usr/lib/python3.6/site-packages/rose2-1.1.0-py3.6.egg/rose2/__init__.py", line 22, in <module>
    from . import genemapper, utils
  File "/usr/lib/python3.6/site-packages/rose2-1.1.0-py3.6.egg/rose2/genemapper.py", line 41, in <module>
    from string import join
ImportError: cannot import name 'join'

```

**Comment by VincentGardeux** [comment]
This was resolved.
It was a conflict between 2 installation on Python2.7 and Python3.6
